<?php

function sum_menu() {
  $items['sum'] = array(
    'title' => 'Calulate Sum',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('sum_form'),
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );
  $items['sum_success_page'] = array(
    'title' => 'Success',
    'page callback' => 'sum_success',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  return $items;
}

function sum_form() {
  $form['left_number'] = array(
    '#title' => 'Left number',
    '#type' => 'textfield',
    '#description' => t('enter a starting number'),
  );

  $form['right_number'] = array(
    '#title' => 'Right number',
    '#type' => 'textfield',
    '#description' => t('enter a number to add'),
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Calculate Sum'
  );

  return $form;
}

function sum_form_submit($form, &$form_state) {
  $n1 = $form_state['values']['left_number'];
  $n2 = $form_state['values']['right_number'];

  $sum = $n1 + $n2;
  $_SESSION['sum_output'] = $sum;

  $form_state['redirect'] = 'sum_success_page';
}

function sum_success() {
  $sum = $_SESSION['sum_output'];
  return 'you did it and got ' . $sum;
}
