<?php
function headlinebacklog_menu() {
  $items = array();
  $items['history'] = array(
    'title' => 'History',
    'page callback' => 'headlinebacklog',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

function headlinebacklog() {

    $history = db_query("SELECT * FROM news_articles;");
    $headlines = '<ul>';
    foreach($history as $headline) {
      $headlines .= '<li>'.$headline->title.'</li>';
    }

  return $headlines.'</ul>';
}
